### ISSUE TITLE
Want a free MySQL database?

### ISSUE THREAD

**Issue by pro6836** [PenguinMod/PenguinMod-BackendApi#4]
Server pixlstudios.eu
Port 3306
Username mythica2_pengmod
Database mythica2_pengdb
Password PengMOD1!
Size Limit IDK, don't use 9999999999999999999999999999999999999999999999999 YottaBytes Tho
Ps - If u want password change, nah

**Comment by pro6836** [comment]
IDC, free db
for idiot

**Comment by dumorando** [comment]
> Ps - If u want password change, nah

skul

**Comment by RedMan13** [comment]
> Server pixlstudios.eu Port 3306 Username mythica2_pengmod Database mythica2_pengdb Password PengMOD1! Size Limit IDK, don't use 9999999999999999999999999999999999999999999999999 YottaBytes Tho Ps - If u want password change, nah

good thing this isnt logged to the public gh logs otherwise you would be COOLED rn :trollface:

**Comment by RedMan13** [comment]
dam girhub has edit history
